var WebAutoVue = (function () {
    function WebAutoVue() {
        this.basedir = "http://192.168.0.38:8080/Autovue/";
        //this.fileBaseDir = 
        this.avSamples = this.basedir + 'PlmFileStorage/';

        // AutoVue Codebase Location
        this.CODEBASE = this.basedir + 'AutoVueClient';

        // AutoVue Server Host
        this.JVUESERVER = this.basedir + 'servlet/VueServlet';

        // JNLP Servlet HOST
        this.JNLP_HOST = this.basedir + 'servlet/VueJNLPServlet';

        // Rendezvous Servlet HOST
        this.RDVSERVLET_HOST = this.basedir + 'servlet/VueRDVServlet';

        this.CL_PRTS = [2345, 7575, 8888];

        // AutoVue Client Parameters
        this.INIT_PARAMS = { 'JVUESERVER': this.JVUESERVER, 'RDVSERVLET': this.RDVSERVLET_HOST, 'VERBOSE': 'true' };

        // Encrypt the cookies by default but don't do it under the Rendez-Vous
        // communication protocol since we cannot safely transmit the decryption key
        this.ENCRYPT_COOKIES = this.RDVSERVLET_HOST == null;

        /*********************** AutoVue JavaScript Object ***********************/
        /*************************************************************************/

        this.myAvApp = new AutoVue(this.JNLP_HOST, this.CODEBASE, this.CL_PRTS, this.INIT_PARAMS, this.ENCRYPT_COOKIES);

        if (this.ENCRYPT_COOKIES && typeof getEncryptionKeys !== 'undefined') {
            // Set Encryption Keys generated by VueKeyPairServlet
            this.myAvApp.setEncryptionKeyPair(getEncryptionKeys().public_key, getEncryptionKeys().private_key);
        }

        this.myAvApp.start(function () { }, function () { }, {});
    }
    return WebAutoVue;
})();

WebAutoVue.prototype.getAutoVue = function () {
    return this.myAvApp;
}

WebAutoVue.prototype.CallAutoVue = function (linkFile) {
    this.myAvApp.setFile(this.avSamples + linkFile);
    
}
